apiVersion: v1
kind: Secret
metadata:
  name: lexiscan-db-secret
type: Opaque
stringData:
  db-user: "admin"
  db-password: "123qwe"
  db-name: "lexiscan_db"
  datasource-url: "jdbc:postgresql://lexiscan-db-service/lexiscan_db"