apiVersion: v1
kind: ConfigMap
metadata:
  name: lexiscan-app-configmap
data:
  application.properties: |
    server:
      port: 8181
    
    spring:
      datasource:
        #    take it from secrets
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
      jpa:
        hibernate:
          ddl-auto: none
        show-sql: true
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
      liquibase:
        change-log: classpath:database/changelog/InitialMigration.xml
        enabled: true
        drop-first: false
        default-schema: public
      thymeleaf:
        cache: false
      application:
        name: lexiscan-app
      servlet:
        multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB
    
    #метрики доступны здесь http://localhost:port/actuator/prometheus
    #source: https://habr.com/ru/articles/548700/
    management:
      endpoints:
        web:
          exposure:
            #add info, metrics
            include: health,prometheus
      metrics:
        distribution:
          percentiles-histogram:
            "[http.server.requests]": true
      prometheus:
        metrics:
          export:
            enabled: true
    
    model:
      url: ${ML_MODEL_URL}
    
    storage:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
