apiVersion: apps/v1
kind: Deployment
metadata:
  name: lexiscan-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lexiscan-app
  template:
    metadata:
      labels:
        app: lexiscan-app
    spec:
      containers:
        - name: lexiscan-app
          image: dashbah/lexiscan-app:latest
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: datasource-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
            - name: ML_MODEL_URL
              value: "http://ml-model-service:5000/predict"
          ports:
            - containerPort: 8181
          volumeMounts:
            - name: spring-application-config
              mountPath: /app/config
            - name: app-volume
              mountPath: /app/build/libs
      volumes:
        - name: app-volume
          emptyDir: {}
        - name: spring-application-config
          configMap:
            name: lexiscan-app-configmap