apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  application.properties: |
    server:
      port: 8181
      #  in bytes - for image uploading
      max-http-request-header-size: 1073741824
    
    spring:
      datasource:
        #    take it from secrets
        url: "jdbc:postgresql://wishlist-db-service/wishlist_db"
        username: admin
        password: 123qwe
      jpa:
        hibernate:
          ddl-auto: none
        show-sql: true
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
      liquibase:
        change-log: classpath:database/changelog/InitialMigration.xml
        enabled: true
        drop-first: false
        default-schema: public
      thymeleaf:
        cache: false
      application:
        name: lexiscan-app
      servlet:
        multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB
    
    #метрики доступны здесь http://localhost:port/actuator/prometheus
    #source: https://habr.com/ru/articles/548700/
    management:
      endpoints:
        web:
          exposure:
            #add info, metrics
            include: health,prometheus
      metrics:
        distribution:
          percentiles-histogram:
            "[http.server.requests]": true
      prometheus:
        metrics:
          export:
            enabled: true
    
    model:
      url: "http://localhost:8282/ml-model/count"
    
    storage:
      url: "jdbc:postgresql://wishlist-db-service/wishlist_db"
      username: admin
      password: 123qwe  
