apiVersion: v1
kind: Service
metadata:
  name: lexiscan-frontend-service
spec:
  selector:
    app: lexiscan-frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3000