apiVersion: v1
kind: Service
metadata:
  name: ml-model-service
spec:
  selector:
    app: ml-model
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8282
      targetPort: 8282
      #nodePort: 31010 #external port