apiVersion: v1
kind: ConfigMap
metadata:
  name: ml-model-configmap
data:
  application.properties: |
    server:
      port: 8282
    
    spring:
      mvc:
        pathmatch:
          matching-strategy: ant_path_matcher
      thymeleaf:
        cache: false
      application:
        name: lexiscan-ml
      servlet:
        multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB
    
    #метрики доступны здесь http://localhost:8181/actuator/prometheus
    #source: https://habr.com/ru/articles/548700/
    management:
      endpoints:
        web:
          exposure:
            #add info, metrics
            include: health,prometheus
      metrics:
        distribution:
          percentiles-histogram:
            "[http.server.requests]": true
      prometheus:
        metrics:
          export:
            enabled: true