apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-model
  template:
    metadata:
      labels:
        app: ml-model
    spec:
      containers:
        - name: ml-model
          image: dashbah/lexiscan-ml-model:latest
          volumeMounts:
            - mountPath: /app/build/libs
              name: ml-model-app-volume
      volumes:
        - name: ml-model-app-volume
          emptyDir: {}