apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  db-user: "admin"
  db-password: "123qwe"
  db-name: "wishlist_db"
  datasource-url: "jdbc:postgresql://wishlist-db-service/wishlist_db"