apiVersion: apps/v1
kind: Deployment
metadata:
  name: wishlist-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wishlist-app
  template:
    metadata:
      labels:
        app: wishlist-app
    spec:
      containers:
        - name: wishlist-app
          image: dashbah/withlist-app-local-macos:latest
#          image: wishlisthse-wishlist-app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8180
          env:
            - name: SERVER_PORT
              value: "8181"
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: datasource-url
          volumeMounts:
            - mountPath: /app/build/libs
              name: app-volume
      volumes:
        - name: app-volume
          emptyDir: {}