apiVersion: v1
kind: Service
metadata:
  name: wishlist-app-service
spec:
  selector:
    app: wishlist-app
  type: LoadBalancer #works only with this type. why?...
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      #nodePort: 31010 #external port